# Generated by Django 4.0.2 on 2022-03-06 15:08

from django.db import migrations, models
import django.utils.timezone
import todoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default=todoapp.models.week_one_hence),
        ),
    ]
