# Generated by Django 4.0.2 on 2022-03-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolist_created_at_todolist_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
