# Generated by Django 4.0.2 on 2022-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_created_at_todolist_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
