# Generated by Django 4.0.2 on 2022-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todolist_options_alter_todolist_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateField(auto_created=True),
        ),
    ]
